### ISSUE TITLE
v1 of the data sync tool

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/data-sync#6]
Version 1 will implement part of the architecture outlined in [the documentation](https://github.com/TwinePlatform/data-sync/blob/master/docs/architecture.md). In particular, version 1 will not implement integrity checking against the target database.

* [x] Visitor app DB ingestion pipeline (#2)
* [x] Admin app DB ingestion pipeline (#5)
* [x] Data merging layer
* [ ] Simple integrity checks layer
* [x] Data output layer
